### ISSUE TITLE
Modernizing the codebase

### ISSUE THREAD

**Issue by rwaldron** [firmata/firmata.js#150]
I've had some work in progress sitting in a stash for a very long time. I tried it out tonight and of course it needed tons of updating. When I got to changing relevant portions of code from function declarations (constructors) to class definitions, mocha exploded: 

```js
Running "mochaTest:files" (mochaTest) task
>> Mocha exploded!
>> SyntaxError: Unexpected reserved word
```

Which is the last effing straw for mocha. I'm going to start rewriting all the tests to use nodeunit.

**Comment by rwaldron** [comment]
On further investigation, it was actually this: 

```diff
-module.exports = com;
+export default com;
```

**Comment by rwaldron** [comment]
I actually didn't mean to close this.

**Comment by rwaldron** [comment]
This is on hold until I can do a study of all projects that depend on Firmata.js and which also stub the constructor with sinon.js

**Comment by Ahmed-90** [comment]
A friendly suggestion is that instead of worrying about all the other projects and how they depends on this module, maybe start clean with firmata2.js or something like that, with all the fancy async/await or maybe even write it in typescript or at least provide native typescript support to make testing easier etc..?

Others can upgrade later whenever they feel like it?

**Comment by rwaldron** [comment]
This has been completed in 2.0.0
