### ISSUE TITLE
Make this repo a monorepo with Lerna

### ISSUE THREAD

**Issue by rwaldron** [firmata/firmata.js#190]
- [x] Publish firmata@1.0.0 in it's exact present form.
- [x] Add lerna.json
- [x] Move current firmata.js code to packages/*
- [x] Split firmata.js into two packages:
  - [x] **firmata-core**: this is most of the current contents of this project, but without an implicit `node-serialport` dependency
  - [x] **firmata.js**: this is just a simple wrapper that "curries" `Firmata` with `Serialport`.
- [x] Publish firmata@2.0.0 and firmata-core@2.0.0

**Comment by dtex** [comment]
Two thoughts:

1. In order to better align with the defacto plugin-io ecosystem naming conventions and reduce confusion between similarly named firmata and firmata.js (which publishes as "firmata" on npm) I propose that we put the mono-repo in a new firmata-io repo and change the package name to "firmata-io". 
1. I worry that adding lerna raises the bar for new contributors but I'm willing to ride right on by this particular windmill.

**Comment by rwaldron** [comment]
@dtex that would mean making a "firmata-io" repo in https://github.com/firmata/, which I think would be strange. I looked at https://github.com/node-serialport/node-serialport and there is no new repo made there.
